AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create DiatonicAdminRole in member accounts'

Parameters:
  ManagementAccountId:
    Type: String
    Default: '313476888312'
    Description: 'Management account ID'

Resources:
  DiatonicAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DiatonicAdminRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub 'arn:aws:iam::${ManagementAccountId}:root'
                - !Sub 'arn:aws:iam::${ManagementAccountId}:user/dfortini-local'
                - !Sub 'arn:aws:iam::${ManagementAccountId}:role/DiatonicCrossAccountManager'
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /
      Tags:
        - Key: Purpose
          Value: CrossAccountAdministration
        - Key: CreatedBy
          Value: DiatonicOrganization
