#!/bin/bash
# Terraform Import Script
# Generated by terraform-audit.sh
#
# This script contains terraform import commands for all unmanaged resources
# Review and execute in appropriate Terraform workspace

set -euo pipefail

echo "=== HIGH PRIORITY IMPORTS ==="
terraform import aws_dynamodb_table.client-billing-data client-billing-data
terraform import aws_dynamodb_table.firespring-backdoor-actions-dev firespring-backdoor-actions-dev
terraform import aws_dynamodb_table.firespring-backdoor-extraction-jobs-dev firespring-backdoor-extraction-jobs-dev
terraform import aws_dynamodb_table.firespring-backdoor-network-state-dev firespring-backdoor-network-state-dev
terraform import aws_dynamodb_table.firespring-backdoor-searches-dev firespring-backdoor-searches-dev
terraform import aws_dynamodb_table.firespring-backdoor-segments-dev firespring-backdoor-segments-dev
terraform import aws_dynamodb_table.firespring-backdoor-traffic-sources-dev firespring-backdoor-traffic-sources-dev
terraform import aws_dynamodb_table.firespring-backdoor-visitors-dev firespring-backdoor-visitors-dev
terraform import aws_dynamodb_table.mmp-toledo-leads-otp-prod mmp-toledo-leads-otp-prod
terraform import aws_dynamodb_table.mmp-toledo-leads-prod mmp-toledo-leads-prod
terraform import aws_dynamodb_table.mmp-toledo-otp-prod mmp-toledo-otp-prod
terraform import aws_vpc.vpc-04864ab584b8852f8 vpc-04864ab584b8852f8
terraform import aws_vpc.vpc-0b2f039c65f685b65 vpc-0b2f039c65f685b65
terraform import aws_vpc.vpc-078018a6669ef0230 vpc-078018a6669ef0230
terraform import aws_vpc.vpc-0879b37db4adabae4 vpc-0879b37db4adabae4
terraform import aws_kms_key.7e72a4d7-45ed-4ba9-995d-bd3b88031c3b 7e72a4d7-45ed-4ba9-995d-bd3b88031c3b
terraform import aws_kms_key.9f763191-e27b-46a1-b879-a1de77da9cbe 9f763191-e27b-46a1-b879-a1de77da9cbe
terraform import aws_kms_key.a8904d6e-2f95-4dc3-a632-b804df3b8230 a8904d6e-2f95-4dc3-a632-b804df3b8230
terraform import aws_kms_key.c9e11579-6f96-4e80-bc84-daa5339c279b c9e11579-6f96-4e80-bc84-daa5339c279b
terraform import aws_kms_key.cc6639db-f56d-4065-83e0-7dd7fc4a0915 cc6639db-f56d-4065-83e0-7dd7fc4a0915
terraform import aws_kms_key.d5f22ef7-d8ff-4b9e-9fce-83a9bb109ad6 d5f22ef7-d8ff-4b9e-9fce-83a9bb109ad6

echo ""
echo "=== MEDIUM PRIORITY IMPORTS ==="
terraform import aws_lambda_function.firespring-backdoor-sync-handler-dev firespring-backdoor-sync-handler-dev
terraform import aws_lambda_function.firespring-backdoor-orchestrator-dev firespring-backdoor-orchestrator-dev
terraform import aws_lambda_function.firespring-backdoor-extractor-dev firespring-backdoor-extractor-dev
terraform import aws_lambda_function.client-billing-costs client-billing-costs
terraform import aws_lambda_function.firespring-backdoor-connector-dev firespring-backdoor-connector-dev
terraform import aws_lambda_function.mmp-toledo-leads-submit-lead mmp-toledo-leads-submit-lead
terraform import aws_lambda_function.firespring-backdoor-exporter-dev firespring-backdoor-exporter-dev
terraform import aws_lambda_function.partner-central-sync partner-central-sync
terraform import aws_lambda_function.firespring-backdoor-api-discovery-dev firespring-backdoor-api-discovery-dev
terraform import aws_lambda_function.client-billing-payment client-billing-payment
terraform import aws_lambda_function.mmp-toledo-submit-lead mmp-toledo-submit-lead
terraform import aws_lambda_function.mmp-toledo-otp-service mmp-toledo-otp-service
terraform import aws_lambda_function.firespring-backdoor-network-manager-dev firespring-backdoor-network-manager-dev
terraform import aws_lambda_function.firespring-backdoor-normalizer-dev firespring-backdoor-normalizer-dev
terraform import aws_lambda_function.mmp-toledo-leads-otp-service mmp-toledo-leads-otp-service
terraform import aws_lambda_function.firespring-backdoor-health-checker-dev firespring-backdoor-health-checker-dev
terraform import aws_s3_bucket.client-billing-reports-313476888312 client-billing-reports-313476888312
terraform import aws_s3_bucket.firespring-backdoor-data-30511389 firespring-backdoor-data-30511389
terraform import aws_s3_bucket.firespring-backdoor-lambda-30511389 firespring-backdoor-lambda-30511389
terraform import aws_s3_bucket.mmp-toledo-billing-portal mmp-toledo-billing-portal
terraform import aws_api_gateway_rest_api.4rqx1r4jzi 4rqx1r4jzi
terraform import aws_api_gateway_rest_api.2ljfykr22k 2ljfykr22k
terraform import aws_api_gateway_rest_api.apw8coizxk apw8coizxk
terraform import aws_api_gateway_rest_api.xnqz4ow8hi xnqz4ow8hi
terraform import aws_secretsmanager_secret.firespring-backdoor_credentials_dev firespring-backdoor/credentials/dev
terraform import aws_secretsmanager_secret.mmp-toledo-leads_sms mmp-toledo-leads/sms
terraform import aws_secretsmanager_secret.mmp-toledo-leads_monday-api mmp-toledo-leads/monday-api
terraform import aws_secretsmanager_secret.mmp-toledo-leads_ses mmp-toledo-leads/ses
terraform import aws_secretsmanager_secret.client-billing_stripe-api-key client-billing/stripe-api-key
terraform import aws_secretsmanager_secret.client-portal_development_stripe-secret client-portal/development/stripe-secret
terraform import aws_secretsmanager_secret.client-portal_development_jwt-secret client-portal/development/jwt-secret
terraform import aws_secretsmanager_secret.client-portal_development_from-email client-portal/development/from-email

echo ""
echo "=== LOW PRIORITY IMPORTS ==="
terraform import aws_cloudwatch_log_group.aws_apigateway_firespring-backdoor-api /aws/apigateway/firespring-backdoor-api
terraform import aws_cloudwatch_log_group.aws_apigateway_mmp-toledo-leads-api /aws/apigateway/mmp-toledo-leads-api
terraform import aws_cloudwatch_log_group.aws_apigateway_welcome /aws/apigateway/welcome
terraform import aws_cloudwatch_log_group.aws_events_firespring-backdoor-health-events /aws/events/firespring-backdoor-health-events
terraform import aws_cloudwatch_log_group.aws_lambda_client-billing-costs /aws/lambda/client-billing-costs
terraform import aws_cloudwatch_log_group.aws_lambda_client-billing-payment /aws/lambda/client-billing-payment
terraform import aws_cloudwatch_log_group.aws_lambda_firespring-backdoor-api-discovery-dev /aws/lambda/firespring-backdoor-api-discovery-dev
terraform import aws_cloudwatch_log_group.aws_lambda_firespring-backdoor-connector-dev /aws/lambda/firespring-backdoor-connector-dev
terraform import aws_cloudwatch_log_group.aws_lambda_firespring-backdoor-exporter-dev /aws/lambda/firespring-backdoor-exporter-dev
terraform import aws_cloudwatch_log_group.aws_lambda_firespring-backdoor-extractor-dev /aws/lambda/firespring-backdoor-extractor-dev
terraform import aws_cloudwatch_log_group.aws_lambda_firespring-backdoor-health-checker-dev /aws/lambda/firespring-backdoor-health-checker-dev
terraform import aws_cloudwatch_log_group.aws_lambda_firespring-backdoor-network-manager-dev /aws/lambda/firespring-backdoor-network-manager-dev
terraform import aws_cloudwatch_log_group.aws_lambda_firespring-backdoor-normalizer-dev /aws/lambda/firespring-backdoor-normalizer-dev
terraform import aws_cloudwatch_log_group.aws_lambda_firespring-backdoor-orchestrator-dev /aws/lambda/firespring-backdoor-orchestrator-dev
terraform import aws_cloudwatch_log_group.aws_lambda_firespring-backdoor-sync-handler-dev /aws/lambda/firespring-backdoor-sync-handler-dev
terraform import aws_cloudwatch_log_group.aws_lambda_mmp-toledo-leads-otp-service /aws/lambda/mmp-toledo-leads-otp-service
terraform import aws_cloudwatch_log_group.aws_lambda_mmp-toledo-leads-submit-lead /aws/lambda/mmp-toledo-leads-submit-lead
terraform import aws_cloudwatch_log_group.aws_lambda_mmp-toledo-otp-service /aws/lambda/mmp-toledo-otp-service
terraform import aws_cloudwatch_log_group.aws_lambda_mmp-toledo-submit-lead /aws/lambda/mmp-toledo-submit-lead
terraform import aws_cloudwatch_log_group.aws_lambda_partner-central-sync /aws/lambda/partner-central-sync
terraform import aws_cloudwatch_log_group.api-gateway-execution-logs_4rqx1r4jzi_prod API-Gateway-Execution-Logs_4rqx1r4jzi/prod
terraform import aws_cloudwatch_event_rule.aws-devops-dev-cf-ssl-certificate-renewal aws-devops-dev-cf-ssl-certificate-renewal
terraform import aws_cloudwatch_event_rule.firespring-backdoor-extraction-schedule firespring-backdoor-extraction-schedule
terraform import aws_cloudwatch_event_rule.firespring-backdoor-network-idle-check firespring-backdoor-network-idle-check
terraform import aws_cloudwatch_event_rule.partner-central-sync-schedule partner-central-sync-schedule
terraform import aws_sns_topic.arn_aws_sns_us-east-1_313476888312_firespring-backdoor-alerts-dev arn:aws:sns:us-east-1:313476888312:firespring-backdoor-alerts-dev
terraform import aws_sqs_queue.https_sqs_us-east-1_amazonaws_com_313476888312_firespring-backdoor-dlq https://sqs.us-east-1.amazonaws.com/313476888312/firespring-backdoor-dlq
