#!/bin/bash

echo "=== Complete Cross-Account Access Setup ==="
echo ""
echo "Since AWS root accounts cannot assume IAM roles, here are your options:"
echo ""
echo "OPTION 1: Console Access (Recommended)"
echo "========================================="
echo ""
echo "For Account 824156498500 (Diatonic Online):"
echo "1. Log into AWS Console with root credentials for aws+diatonic-online@dacvisuals.com"
echo "2. Navigate to IAM > Roles > OrganizationAccountAccessRole"
echo "3. Click 'Trust relationships' tab > Edit trust policy"
echo "4. Replace with this trust policy:"
echo ""
cat /tmp/org-role-trust-policy.json
echo ""
echo ""
echo "For Account 842990485193 (Diatonic AI):"
echo "1. Log into AWS Console with root credentials for aws+diatonic-ai@dacvisuals.com"
echo "2. Navigate to IAM > Roles > OrganizationAccountAccessRole"
echo "3. Click 'Trust relationships' tab > Edit trust policy"
echo "4. Replace with the same trust policy as above"
echo ""
echo ""
echo "OPTION 2: CLI Access (If you have credentials)"
echo "=============================================="
echo ""
echo "If you have CLI credentials for each account, run:"
echo ""
echo "# For account 824:"
echo "aws iam update-assume-role-policy \\"
echo "  --role-name OrganizationAccountAccessRole \\"
echo "  --policy-document file:///tmp/org-role-trust-policy.json \\"
echo "  --profile [your-824-profile]"
echo ""
echo "# For account 842:"
echo "aws iam update-assume-role-policy \\"
echo "  --role-name OrganizationAccountAccessRole \\"
echo "  --policy-document file:///tmp/org-role-trust-policy.json \\"
echo "  --profile [your-842-profile]"
echo ""
echo ""
echo "VERIFICATION:"
echo "============"
echo "After updating both accounts, test access with:"
echo "  aws sts get-caller-identity --profile online-824"
echo "  aws sts get-caller-identity --profile mgmt-842"
echo ""
echo "Both commands should succeed and show assumed role ARNs."
