#!/bin/bash

echo "🔧 Setting up cross-account access using dfortini-local admin user..."
echo ""

# Test current access to target accounts
echo "Testing current access to target accounts..."
echo ""

echo "Testing account 824 access:"
aws sts get-caller-identity --profile online-824 2>&1 || echo "❌ Cannot access account 824 yet"

echo ""
echo "Testing account 842 access:"
aws sts get-caller-identity --profile mgmt-842 2>&1 || echo "❌ Cannot access account 842 yet"

echo ""
echo "SOLUTION OPTIONS:"
echo "================="
echo ""
echo "OPTION 1: Manual Console Update (RECOMMENDED)"
echo "---------------------------------------------"
echo "Since AWS root accounts cannot assume roles, you need to:"
echo ""
echo "1. Login to AWS Console with root credentials for each account:"
echo "   - Account 824: aws+diatonic-online@dacvisuals.com"
echo "   - Account 842: aws+diatonic-ai@dacvisuals.com"
echo ""
echo "2. In each account console:"
echo "   - Go to IAM → Roles → OrganizationAccountAccessRole"
echo "   - Click Trust Relationships → Edit Trust Policy"
echo "   - Replace with this trust policy (WITHOUT root principal):"
echo ""
cat /tmp/org-role-trust-policy-fixed.json
echo ""
echo ""
echo "OPTION 2: Create New IAM Users (ALTERNATIVE)"
echo "--------------------------------------------"
echo "If you prefer separate IAM users in each account:"
echo ""
echo "For Account 824 (Diatonic Online):"
echo "1. Login as root to account 824"
echo "2. IAM → Users → Create User → 'dfortini-admin-824'"
echo "3. Enable Console + Programmatic access"
echo "4. Attach AdministratorAccess policy"
echo "5. Download credentials and configure:"
echo "   aws configure --profile dfortini-824"
echo ""
echo "For Account 842 (Diatonic AI):"
echo "1. Login as root to account 842"
echo "2. IAM → Users → Create User → 'dfortini-admin-842'"
echo "3. Enable Console + Programmatic access"
echo "4. Attach AdministratorAccess policy"
echo "5. Download credentials and configure:"
echo "   aws configure --profile dfortini-842"
echo ""
echo "VERIFICATION:"
echo "============"
echo "After either option, test access with:"
echo "  aws sts get-caller-identity --profile online-824"
echo "  aws sts get-caller-identity --profile mgmt-842"
echo ""
echo "Both should show assumed role ARNs (Option 1) or user ARNs (Option 2)."

